/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package supermarket;

import java.awt.Color;
import java.awt.Cursor;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author SampritBiswas
 */
public class ManagerGui extends javax.swing.JFrame {

    /**
     * Creates new form ManagerGui
     */
    public ManagerGui() {
        initComponents();
        setLocation(450, 200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        viewItemsButton = new javax.swing.JButton();
        viewSalesButton = new javax.swing.JButton();
        changePriceButton = new javax.swing.JButton();
        itemsRequired = new javax.swing.JButton();
        addNewItemButton = new javax.swing.JButton();
        newEmployeeButton = new javax.swing.JButton();
        logoutLabel = new javax.swing.JLabel();
        accountLabel = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        viewItemsButton.setText("View Items in SuperMarket");
        viewItemsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewItemsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewItemsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewItemsButtonMouseExited(evt);
            }
        });
        viewItemsButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                viewItemsButtonMouseMoved(evt);
            }
        });
        viewItemsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewItemsButtonActionPerformed(evt);
            }
        });
        viewItemsButton.setBounds(110, 50, 180, 32);
        jLayeredPane1.add(viewItemsButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        viewSalesButton.setText("View Sales Statistics");
        viewSalesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewSalesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewSalesButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewSalesButtonMouseExited(evt);
            }
        });
        viewSalesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSalesButtonActionPerformed(evt);
            }
        });
        viewSalesButton.setBounds(110, 100, 180, 32);
        jLayeredPane1.add(viewSalesButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        changePriceButton.setText("Change price of an item");
        changePriceButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changePriceButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changePriceButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                changePriceButtonMouseExited(evt);
            }
        });
        changePriceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePriceButtonActionPerformed(evt);
            }
        });
        changePriceButton.setBounds(110, 150, 180, 32);
        jLayeredPane1.add(changePriceButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        itemsRequired.setText("View Items Required");
        itemsRequired.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemsRequired.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                itemsRequiredMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                itemsRequiredMouseExited(evt);
            }
        });
        itemsRequired.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemsRequiredActionPerformed(evt);
            }
        });
        itemsRequired.setBounds(110, 200, 180, 32);
        jLayeredPane1.add(itemsRequired, javax.swing.JLayeredPane.DEFAULT_LAYER);

        addNewItemButton.setText("Add new Item");
        addNewItemButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addNewItemButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addNewItemButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addNewItemButtonMouseExited(evt);
            }
        });
        addNewItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewItemButtonActionPerformed(evt);
            }
        });
        addNewItemButton.setBounds(110, 250, 180, 32);
        jLayeredPane1.add(addNewItemButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        newEmployeeButton.setText("Add New Employee");
        newEmployeeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newEmployeeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newEmployeeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newEmployeeButtonMouseExited(evt);
            }
        });
        newEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEmployeeButtonActionPerformed(evt);
            }
        });
        newEmployeeButton.setBounds(110, 300, 180, 32);
        jLayeredPane1.add(newEmployeeButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        logoutLabel.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        logoutLabel.setForeground(new java.awt.Color(255, 0, 0));
        logoutLabel.setText("Logout");
        logoutLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutLabelMouseExited(evt);
            }
        });
        logoutLabel.setBounds(320, 10, 52, 17);
        jLayeredPane1.add(logoutLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        accountLabel.setBackground(new java.awt.Color(255, 255, 255));
        accountLabel.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        accountLabel.setForeground(new java.awt.Color(0, 0, 204));
        accountLabel.setText("Your Account");
        accountLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        accountLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accountLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accountLabelMouseExited(evt);
            }
        });
        accountLabel.setBounds(10, 10, 94, 17);
        jLayeredPane1.add(accountLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        welcomeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setBounds(130, 10, 152, 20);
        jLayeredPane1.add(welcomeLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supermarket/images/im15.jpg"))); // NOI18N
        jLabel2.setBounds(-6, 0, 400, 380);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accountLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountLabelMouseClicked
        NewEmployeeGUI nemp = new NewEmployeeGUI();
        nemp.viewProfile = true;
        nemp.setFields(manager);
        nemp.setVisible(true);
        nemp.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }//GEN-LAST:event_accountLabelMouseClicked

    private void logoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseClicked
        FirstScreenGUI fsg = new FirstScreenGUI();
        setVisible(false);
        fsg.setVisible(true);
        fsg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_logoutLabelMouseClicked

    private void changePriceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePriceButtonActionPerformed
        Object[] options = {"Change Single Item",
            "Change Bulk Item"};
        int n = JOptionPane.showOptionDialog(new JFrame(),
                "What would you like to do ?",
                "Change Price",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]);
        if (n == 0) {
            String str = JOptionPane.showInputDialog(null, "Enter the Item ID : ",
                    "Change Price", JOptionPane.QUESTION_MESSAGE);
            ArrayList<Item> arr = new GetInfoFromFiles().getItems();
            int temp = 0;
            for (Item i : arr) {

                if (i.getID().equalsIgnoreCase(str)) {
                    str = JOptionPane.showInputDialog(null, "The old purchase price is : " + i.getPurchasePrice() + "\nEnter the new Price : ",
                            "Change Price", JOptionPane.QUESTION_MESSAGE);
                    i.setPurchasePrice(Integer.parseInt(str));
                    str = JOptionPane.showInputDialog(null, "The old sell price is : " + i.getSellPrice() + "\nEnter the new Price : ",
                            "Change Price", JOptionPane.QUESTION_MESSAGE);
                    i.setSellPrice(Integer.parseInt(str));
                    temp = 1;
                    try {
                        FileOutputStream fileStream = new FileOutputStream("DataBase.ser");
                        ObjectOutputStream os = new ObjectOutputStream(fileStream);
                        os.writeObject(arr);
                        os.close();
                    } catch (IOException ex) {
                        System.out.println("\nFile Not Found!!!");
                        ex.printStackTrace();
                    }

                    WriteToServer wr = new WriteToServer();
                    wr.writeDataBase();
                    break;
                }

            }
            if (temp == 0) {
                JOptionPane.showMessageDialog(this, "Incorrect Item_id!");
            }
        } else {
            PrintItemsGUI changeitem;

            changeitem = new PrintItemsGUI(1);
            changeitem.setVisible(true);
            changeitem.itemTypeButton.setVisible(false);
            changeitem.manufacturerButton.setVisible(false);
            changeitem.resetButton.setVisible(false);
            changeitem.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);

        }
    }//GEN-LAST:event_changePriceButtonActionPerformed

    private void changePriceButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePriceButtonMouseExited
        changePriceButton.setForeground(Color.BLACK);
    }//GEN-LAST:event_changePriceButtonMouseExited

    private void changePriceButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePriceButtonMouseEntered
        changePriceButton.setForeground(Color.red);
    }//GEN-LAST:event_changePriceButtonMouseEntered

    private void viewSalesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSalesButtonActionPerformed

        ViewSalesGUI view = new ViewSalesGUI();
        view.setVisible(false);
        view.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        //view.setLocation(450, 200);
    }//GEN-LAST:event_viewSalesButtonActionPerformed

    private void viewSalesButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewSalesButtonMouseExited
        viewSalesButton.setForeground(Color.BLACK);
    }//GEN-LAST:event_viewSalesButtonMouseExited

    private void viewSalesButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewSalesButtonMouseEntered
        viewSalesButton.setForeground(Color.red);
    }//GEN-LAST:event_viewSalesButtonMouseEntered

    private void newEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEmployeeButtonActionPerformed
        NewEmployeeGUI newEmp = new NewEmployeeGUI();
        newEmp.setVisible(true);
        newEmp.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        newEmp.setLocation(450, 200);
    }//GEN-LAST:event_newEmployeeButtonActionPerformed

    private void newEmployeeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newEmployeeButtonMouseExited
        newEmployeeButton.setForeground(Color.black);
    }//GEN-LAST:event_newEmployeeButtonMouseExited

    private void newEmployeeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newEmployeeButtonMouseEntered
        newEmployeeButton.setForeground(Color.red);
    }//GEN-LAST:event_newEmployeeButtonMouseEntered

    private void addNewItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewItemButtonActionPerformed
        NewItemGUI newItem = new NewItemGUI();
        newItem.setVisible(true);
        newItem.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }//GEN-LAST:event_addNewItemButtonActionPerformed

    private void addNewItemButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNewItemButtonMouseExited
        addNewItemButton.setForeground(Color.BLACK);
    }//GEN-LAST:event_addNewItemButtonMouseExited

    private void addNewItemButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNewItemButtonMouseEntered
        addNewItemButton.setForeground(Color.red);
    }//GEN-LAST:event_addNewItemButtonMouseEntered

    private void viewItemsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewItemsButtonActionPerformed

        viewItemsButton.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        PrintItemsGUI p;

        p = new PrintItemsGUI(0);
        p.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        p.setVisible(true);

        viewItemsButton.setCursor(new Cursor(Cursor.HAND_CURSOR));


    }//GEN-LAST:event_viewItemsButtonActionPerformed

    private void viewItemsButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewItemsButtonMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_viewItemsButtonMouseMoved

    private void viewItemsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewItemsButtonMouseExited
        viewItemsButton.setForeground(Color.BLACK);
        viewItemsButton.setVisible(true);

    }//GEN-LAST:event_viewItemsButtonMouseExited

    private void viewItemsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewItemsButtonMouseEntered
        viewItemsButton.setForeground(Color.red);

    }//GEN-LAST:event_viewItemsButtonMouseEntered

    private void itemsRequiredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemsRequiredActionPerformed
        RequiredItemsGUI req = new RequiredItemsGUI();
        req.setVisible(true);
    }//GEN-LAST:event_itemsRequiredActionPerformed

    private void itemsRequiredMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemsRequiredMouseExited
        itemsRequired.setForeground(Color.BLACK);
    }//GEN-LAST:event_itemsRequiredMouseExited

    private void itemsRequiredMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemsRequiredMouseEntered
        itemsRequired.setForeground(Color.red);
    }//GEN-LAST:event_itemsRequiredMouseEntered

    private void accountLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountLabelMouseEntered
        accountLabel.setBackground(Color.pink);
        accountLabel.setOpaque(true);
    }//GEN-LAST:event_accountLabelMouseEntered

    private void accountLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountLabelMouseExited
        accountLabel.setBackground(Color.white);
        accountLabel.setOpaque(false);
    }//GEN-LAST:event_accountLabelMouseExited

    private void logoutLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseEntered
        logoutLabel.setBackground(new Color(50, 200, 200));
        logoutLabel.setOpaque(true);
    }//GEN-LAST:event_logoutLabelMouseEntered

    private void logoutLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseExited
        logoutLabel.setBackground(Color.white);
        logoutLabel.setOpaque(false);
    }//GEN-LAST:event_logoutLabelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerGui().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountLabel;
    private javax.swing.JButton addNewItemButton;
    private javax.swing.JButton changePriceButton;
    private javax.swing.JButton itemsRequired;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JButton newEmployeeButton;
    private javax.swing.JButton viewItemsButton;
    private javax.swing.JButton viewSalesButton;
    public javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
    Employee manager = new Employee();
}
