/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package supermarket;

import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author SampritBiswas
 */
public class NewEmployeeGUI extends javax.swing.JFrame {

    /**
     * Creates new form NewEmployeeGUI
     */
    public NewEmployeeGUI() {
        initComponents();
        allowCheck.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        addText = new javax.swing.JTextField();
        usernameText = new javax.swing.JTextField();
        passwordText = new javax.swing.JTextField();
        contactText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dropBox = new javax.swing.JComboBox();
        submitButton = new javax.swing.JButton();
        allowCheck = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name");

        jLabel2.setText("Address");

        jLabel3.setText("username");

        jLabel4.setText("password");

        jLabel5.setText("contact number");

        jLabel6.setText("Type");

        dropBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manager", "Sales Clerk" }));
        dropBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropBoxActionPerformed(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        allowCheck.setText("Allow Sales Clerk to add items to database");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameText)
                                    .addComponent(addText)
                                    .addComponent(usernameText)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(54, 54, 54)
                                .addComponent(passwordText))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(allowCheck)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(25, 25, 25)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(dropBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(60, 60, 60))
                                            .addComponent(contactText))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(addText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(usernameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(contactText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dropBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(allowCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(submitButton))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        if (!addText.getText().equals("") && !contactText.getText().equals("") && !nameText.getText().equals("") && !passwordText.getText().equals("") && !usernameText.getText().equals("")) {
            Employee emp = new Employee();
            ArrayList<Employee> arr = new GetInfoFromFiles().getEmployeeInfo();
            if (viewProfile == true) {

                for (Employee e : arr) {
                    if (e.getUsername().equalsIgnoreCase(usernameText.getText())) {
                        if (e.getPassword().equalsIgnoreCase(passwordText.getText())) {
                            emp = e;
                            if (allowCheck.isSelected() == true) {
                                emp.allowWrite = true;
                            } else {
                                emp.allowWrite = false;
                            }
                            break;
                        }
                    }
                }
            } else {

                for (Employee e : arr) {
                    if (e.getUsername().equalsIgnoreCase(usernameText.getText())) {

                        JOptionPane.showMessageDialog(this, "Username already exists!!!");
                        return;
                    }
                }
            }
            emp.setAddress(addText.getText());
            emp.setContactNo(contactText.getText());
            emp.setName(nameText.getText());
            emp.setPassword(passwordText.getText());
            emp.setUsername(usernameText.getText());
            if (allowCheck.isSelected() == true) {
                emp.allowWrite = true;
            } else {
                emp.allowWrite = false;
            }

            String sel = (String) dropBox.getSelectedItem();
            boolean set;
            if (sel.equalsIgnoreCase("manager")) {
                set = true;
                if (clerk == true) {
                    set = false;
                    JOptionPane.showMessageDialog(this, "Cannot change type!!!");
                }
            } else {
                set = false;
            }
            emp.setAccessData(set);
            if (viewProfile == false) {
                emp.addNewEmployee();
            } else {
                try {
                    FileOutputStream fileStream = new FileOutputStream("Employee.ser");
                    ObjectOutputStream os = new ObjectOutputStream(fileStream);
                    os.writeObject(arr);
                    os.close();
                } catch (IOException ex) {
                    System.out.println("\nFile Not Found!!!");
                    ex.printStackTrace();
                }

                try {
                    WriteToServer wr = new WriteToServer();
                    wr.writeEmployee();
                } catch (Exception e) {
                }

            }
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "No Fields Shoud Be Left Empty!!");
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void dropBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropBoxActionPerformed
        if (dropBox.getSelectedItem().toString().equalsIgnoreCase("Sales Clerk")) {
            allowCheck.setVisible(true);
        } else {
            allowCheck.setVisible(false);
        }
    }//GEN-LAST:event_dropBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewEmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewEmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewEmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewEmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewEmployeeGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addText;
    private javax.swing.JCheckBox allowCheck;
    private javax.swing.JTextField contactText;
    private javax.swing.JComboBox dropBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField passwordText;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField usernameText;
    // End of variables declaration//GEN-END:variables
    boolean viewProfile = false;
    boolean clerk = false;

    public void setFields(Employee e) {
        nameText.setText(e.getName());
        addText.setText(e.getAddress());
        usernameText.setText(e.getUsername());
        passwordText.setText(e.getPassword());
        contactText.setText(e.getContactNo());
        if (e.getAccessDate() == true) {
            dropBox.setSelectedItem("Manager");
        } else {
            dropBox.setSelectedIndex(1);
            clerk = true;
        }
    }
}
