/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package supermarket;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author SampritBiswas
 */
public class SalesClerkGUI extends javax.swing.JFrame {

    /**
     * Creates new form SalesClerkGUI
     */
    public SalesClerkGUI() {
        initComponents();
        setLocation(450, 200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        addNewItemButton = new javax.swing.JButton();
        getItemsButton = new javax.swing.JButton();
        accountLabel = new javax.swing.JLabel();
        logoutLabel = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addNewItemButton.setText("Add new Item");
        addNewItemButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addNewItemButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addNewItemButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addNewItemButtonMouseExited(evt);
            }
        });
        addNewItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewItemButtonActionPerformed(evt);
            }
        });
        addNewItemButton.setBounds(120, 170, 180, 40);
        jLayeredPane1.add(addNewItemButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getItemsButton.setText("Get Items from customer");
        getItemsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getItemsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                getItemsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                getItemsButtonMouseExited(evt);
            }
        });
        getItemsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getItemsButtonActionPerformed(evt);
            }
        });
        getItemsButton.setBounds(120, 80, 180, 40);
        jLayeredPane1.add(getItemsButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        accountLabel.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        accountLabel.setForeground(new java.awt.Color(0, 0, 255));
        accountLabel.setText("Your Account");
        accountLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        accountLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accountLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accountLabelMouseExited(evt);
            }
        });
        accountLabel.setBounds(10, 10, 98, 17);
        jLayeredPane1.add(accountLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        logoutLabel.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        logoutLabel.setForeground(new java.awt.Color(204, 0, 0));
        logoutLabel.setText("Logout");
        logoutLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutLabelMouseExited(evt);
            }
        });
        logoutLabel.setBounds(320, 10, 52, 17);
        jLayeredPane1.add(logoutLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        welcomeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setBounds(130, 10, 146, 17);
        jLayeredPane1.add(welcomeLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supermarket/images/im11.jpg"))); // NOI18N
        jLabel1.setBounds(-6, 0, 410, 280);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addNewItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewItemButtonActionPerformed
        NewItemGUI newItem = new NewItemGUI();
        newItem.setVisible(true);
        newItem.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }//GEN-LAST:event_addNewItemButtonActionPerformed

    private void getItemsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getItemsButtonActionPerformed
        GetItemsFromCustomer get = new GetItemsFromCustomer();
        get.setVisible(true);
        get.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        get.emp = sales;
    }//GEN-LAST:event_getItemsButtonActionPerformed

    private void logoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseClicked
        FirstScreenGUI fsg=new FirstScreenGUI();
        setVisible(false);
        fsg.setVisible(true);
        fsg.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }//GEN-LAST:event_logoutLabelMouseClicked

    private void accountLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountLabelMouseClicked
        NewEmployeeGUI newEmp = new NewEmployeeGUI();
        newEmp.viewProfile = true;
        newEmp.setVisible(true);
        newEmp.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        newEmp.setFields(sales);
        
    }//GEN-LAST:event_accountLabelMouseClicked

    private void accountLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountLabelMouseEntered
        accountLabel.setBackground(Color.pink);
        accountLabel.setOpaque(true);
    }//GEN-LAST:event_accountLabelMouseEntered

    private void accountLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountLabelMouseExited
        accountLabel.setBackground(Color.white);
        accountLabel.setOpaque(false);
    }//GEN-LAST:event_accountLabelMouseExited

    private void logoutLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseEntered
        logoutLabel.setBackground(new Color(50, 200, 200));
        logoutLabel.setOpaque(true);
    }//GEN-LAST:event_logoutLabelMouseEntered

    private void logoutLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseExited
        logoutLabel.setBackground(Color.white);
        logoutLabel.setOpaque(false);
    }//GEN-LAST:event_logoutLabelMouseExited

    private void getItemsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getItemsButtonMouseEntered
        getItemsButton.setForeground(Color.red);
    }//GEN-LAST:event_getItemsButtonMouseEntered

    private void getItemsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getItemsButtonMouseExited
        getItemsButton.setForeground(Color.black);
    }//GEN-LAST:event_getItemsButtonMouseExited

    private void addNewItemButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNewItemButtonMouseEntered
        addNewItemButton.setForeground(Color.red);
    }//GEN-LAST:event_addNewItemButtonMouseEntered

    private void addNewItemButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNewItemButtonMouseExited
        addNewItemButton.setForeground(Color.black);
    }//GEN-LAST:event_addNewItemButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesClerkGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesClerkGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesClerkGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesClerkGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesClerkGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountLabel;
    public javax.swing.JButton addNewItemButton;
    private javax.swing.JButton getItemsButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel logoutLabel;
    public javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
    
    Employee sales = new Employee();
}
